export const SHORTEN_LINK = 'SHORTEN_LINK'
export const SHORTEN_LINK_REQUEST = 'SHORTEN_LINK_REQUEST'
export const SHORTEN_LINK_SUCCESS = 'SHORTEN_LINK_SUCCESS'
export const SHORTEN_LINK_FAILURE = 'SHORTEN_LINK_FAILURE'

export const VALIDATE_URL = 'VALIDATE_URL'
